IbnFadlan/Models/TrendLineViewModel.cs
using System;
using System.Collections.Generic;
using IbnFadlan.Business.Services.Enums;

namespace IbnFadlan.Models
{
    public class TrendLineViewModel
    {
        public string CountryName { get; set; }

        public IList<int> From { get; set; }

        public IList<int> To { get; set; }

        public IList<int> Years { get; set; }

        public List<List<int>> Clusters { get; set; }
    }
}

IbnFadlan/Controllers/HomeController.cs
using System.Web.Mvc;
using IbnFadlan.Business.Services.Enums;

namespace IbnFadlan.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Charts(string country, Direction direction, int? year)
        {
            return View(new ChartSetViewModel(country, direction, year));
        }

        public ActionResult Bf()
        {
            return RedirectToAction("Charts", new { country = "Belarus", direction = Direction.From});
        }

        public ActionResult Bt()
        {
            return RedirectToAction("Charts", new { country = "Belarus", direction = Direction.To });
        }

        public ActionResult TrendLines()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }

    public class ChartSetViewModel
    {
        public ChartSetViewModel(string country, Direction direction, int? year)
        {
            Country = country;
            Direction = direction;
            Year = year;
        }

        public string Country { get; set; }
        public Direction Direction { get; set; }
        public int? Year { get; set; }
    }
}

IbnFadlan/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using IbnFadlan.Algorithm.Search;
using IbnFadlan.Algorithm.Trend;
using IbnFadlan.Business;
using IbnFadlan.Business.Services.Enums;
using IbnFadlan.Models;

namespace IbnFadlan.Controllers
{
    public class StatisticController : Controller
    {
        private readonly StatisticService _statisticService;

        public StatisticController()
        {
            _statisticService = new StatisticService();
        }

        public ActionResult PieChart(string country, Direction direction, int? year)
        {
            var data = _statisticService.GetData(country, direction, year);

            return View(data);
        }

        public ActionResult Map(string country, Direction direction, int? year)
        {
            var data = _statisticService.GetClusteredData(country, direction, year);

            return View(data);
        }

        public ActionResult MapClusters(string country, Direction direction, int? year)
        {
            var data = _statisticService.GetClusteredData(country, direction, year);

            return View(data);
        }

        public ActionResult TreeMap(string country, Direction direction, int? year)
        {
            var data = _statisticService.GetClusteredData(country, direction, year);

            return View(data);
        }

        public ActionResult TrendLine(string country)
        {
            var from = _statisticService.GetFullData(country, Direction.From);
            var to = _statisticService.GetFullData(country, Direction.To);

            var years = from.Keys.Union(to.Keys).Distinct().ToList();

            var fromValues = from.Values.ToList();
            var toValues = to.Values.ToList();

            var trendLineFrom = new TrendLineLinear(years.Select(x => (double) x),
                fromValues.Select(x => (double) x));
            
            var additionalYears = new List<int>
            {
                2020,
                2025,
                2030
            };
            
            var trendLineTo = new TrendLineLinear(years.Select(x => (double)x),
                toValues.Select(x => (double)x));

            fromValues
                .AddRange(trendLineFrom.GetGrowth(additionalYears.Select(x => (double)x).ToList())
                .Select(x => (int)x));

            toValues
                .AddRange(trendLineTo.GetGrowth(additionalYears.Select(x => (double)x).ToList())
                    .Select(x => (int)x));

            years.AddRange(additionalYears);

            var vm = new TrendLineViewModel
            {
                CountryName = country,
                From = fromValues,
                To = toValues,
                Years = years
            };
            
            return View(vm);
        }
    }
}

IbnFadlan/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

IbnFadlan/Views/Home/Charts.cshtml
@model IbnFadlan.Controllers.ChartSetViewModel
@{
    ViewBag.Title = Model.Direction.ToString("G");
}

<p>
    @Html.Action("Index", "Home")
</p>

<div class="row">
    <div class="col-md-4">
        <h2>Immigration @Model.Direction.ToString("G") @Model.Country @(Model.Year.HasValue ? string.Format("in {0} year", Model.Year) : "")</h2>
        <p>
            @Html.Action("PieChart", "Statistic", new { country = Model.Country, direction = Model.Direction, year = Model.Year })
        </p>
        <p>
            @Html.Action("Map", "Statistic", new { country = Model.Country, direction = Model.Direction, year = Model.Year })
        </p>
        <p>
            @Html.Action("MapClusters", "Statistic", new { country = Model.Country, direction = Model.Direction, year = Model.Year })
        </p>
        <p>
            @Html.Action("TreeMap", "Statistic", new { country = Model.Country, direction = Model.Direction, year = Model.Year })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = Model.Country })
        </p>
    </div>
</div>

IbnFadlan/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IbnFadlan/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <form action="/Home/Charts" method="get">
            <div class="item">
                <label>Country</label>
                <select name="country">
                    <option value="Belarus">Belarus</option>
                    <option value="Poland">Poland</option>
                    <option value="Russian Federation">Russian Federation</option>
                    <option value="Ukraine">Ukraine</option>
                    <option value="Republic of Moldova">Republic of Moldova</option>
                    <option value="Latvia">Latvia</option>
                    <option value="Lithuania">Lithuania</option>
                    <option value="Estonia">Estonia</option>
                    <option value="Germany">Germany</option>
                    <option value="Syrian Arab Republic">Syrian Arab Republic</option>
                    <option value="France">France</option>
                    <option value="Switzerland">Switzerland</option>
                </select> 
            </div>
            <div class="item">
                <label>Direction</label>
                <select name="direction">
                    <option value="0">From</option>
                    <option value="1">To</option>
                </select> 
            </div>
            <div class="item">
                <label>Year</label>
                <select name="year">
                    <option value="null">-</option>
                    <option value="1990">1990</option>
                    <option value="1995">1995</option>
                    <option value="2000">2000</option>
                    <option value="2005">2005</option>
                    <option value="2010">2010</option>
                    <option value="2015">2015</option>
                    <option value="2017">2017</option>
                </select> 
            </div>
            <input type="submit" value="Show" />
        </form>
    </div>
</div>

IbnFadlan/Views/Home/TrendLines.cshtml
@using IbnFadlan.Business.Services.Enums
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h1>Examples</h1>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Belarus"})
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Poland" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Russia" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Ukraine" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Moldova" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Latvia" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Lithuania" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Estonia" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Germany" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "France" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Syria" })
        </p>
        <p>
            @Html.Action("TrendLine", "Statistic", new { country = "Switzerland" })
        </p>
    </div>
</div>